.PHONY: clean All

All:
	@echo "----------Building project:[ NumberGuessing - Debug ]----------"
	@cd "p2" && "$(MAKE)" -f  "NumberGuessing.mk"
clean:
	@echo "----------Cleaning project:[ NumberGuessing - Debug ]----------"
	@cd "p2" && "$(MAKE)" -f  "NumberGuessing.mk" clean
